### ISSUE TITLE
"dikmax-name build" encounter error

### ISSUE THREAD

**Issue by luckypoem** [dikmax/dikmax.name#4]
hi.

root@AR:/usr/local/dikmax.name-site# dikmax-name build

it shows:
...
[ERROR] Hakyll.Core.UnixFilter.unixFilterWith: lessc --clean-css=advanced --autoprefix --include-path=less - gave exit code 1
root@AR:/usr/local/dikmax.name-site#

i already ran "npm install -g less"

how to fix it?tks

**Comment by dikmax** [comment]
To be honest, this repository is for archive purpose only. As I'm aware it won't properly build with the latest version of Dart and, probably, lessc.

You can check what's going wrong with less, try running from project root.

```
lessc --clean-css=advanced --autoprefix --include-path=less less/style.less
```

If you copy error from output here I might help you.

Otherwise, you can check new version at [dikmax/dikmax.name-ng](https://github.com/dikmax/dikmax.name-ng), but it's written with Shake instead of Hakyll.

**Comment by luckypoem** [comment]
hi.

root@AR:/usr/local/dikmax.name-site# lessc --clean-css=advanced --autoprefix --include-path=less less/style.less

it shows:
Unable to interpret argument autoprefix - if it is a plugin (less-plugin-autoprefix), make sure that it is installed under or at the same level as less.

what is the Shake ?where is its git repo?

**Comment by dikmax** [comment]
So error is pretty self-explanatory, you need to install autoprefix plugin:

``` bash
npm install -g less-plugin-autoprefix
```

BTW, if you didn't installed clean-css plugin, you'll see a message about it next, so run:

``` bash
npm install -g less-plugin-clean-css
```

As for shake, here's [repo ndmitchell/shake](https://github.com/ndmitchell/shake) and [official website](http://shakebuild.com/).

**Comment by luckypoem** [comment]
hi.

after i ran "npm install -g less-plugin-autoprefix" and "npm install -g less-plugin-clean-css" and "npm install -g commander",then i ran "dikmax-name build",it shows:
...
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/dikmax.name-site/js/highlight.js/tools/build.js:3:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
  [ERROR] js/highlight.js/build/highlight.pack.js: openFile: does not exist (No such file or directory)
root@AR:/usr/local/dikmax.name-site#

thank you

**Comment by dikmax** [comment]
Open directory `js/highlight.js` and run `npm install`.

The site uses a custom version of highlight.js.

**Comment by luckypoem** [comment]
Open directory js/highlight.js and run npm install.then cd /usr/local/dikmax.name-site

run "dikmax-name  build"  still encounter error:
[ERROR] dart2js: rawSystem: runInteractiveProcess: exec: does not exist (No such file or directory)

tks

**Comment by dikmax** [comment]
Have you installed Dart?

**Comment by luckypoem** [comment]
hi.
 i installed dart,but running "dikmax-name build" still encounter errors:

Error: Library not found 'package:dikmax.name/app.dart'.
import 'package:dikmax.name/app.dart';
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dart/web/map.dart:2:8:
Error: Library not found 'package:dikmax.name/map.dart'.
import 'package:dikmax.name/map.dart';
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dart/web/map.dart:7:3:
Warning: Cannot resolve type 'App'.
  App app = new App();
  ^^^
dart/web/map.dart:7:17:
Warning: Cannot resolve 'App'.
  App app = new App();
                ^^^
dart/web/map.dart:10:3:
Warning: Cannot resolve type 'MapApplication'.
  MapApplication map = new MapApplication();
  ^^^^^^^^^^^^^^
dart/web/map.dart:10:28:
Warning: Cannot resolve 'MapApplication'.
  MapApplication map = new MapApplication();
                           ^^^^^^^^^^^^^^
Error: Compilation failed.
  [ERROR] _temp/script-map.dart.js: openFile: does not exist (No such file or directory)
root@AR:/usr/local/dikmax.name-site#

**Comment by dikmax** [comment]
Ok, forget about Dart for now.

Just comment out [this line](https://github.com/dikmax/dikmax.name/blob/master/src/Site.hs#L39) with `scriptsCompilerRules` call. And it won't try to compile scripts.

**Comment by luckypoem** [comment]
it doesn't work 。
still encounter errors:
Error: Library not found 'package:dikmax.name/app.dart'.
import 'package:dikmax.name/app.dart';
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dart/web/map.dart:2:8:
Error: Library not found 'package:dikmax.name/map.dart'.
import 'package:dikmax.name/map.dart';
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dart/web/map.dart:7:3:
Warning: Cannot resolve type 'App'.
  App app = new App();
  ^^^
dart/web/map.dart:7:17:
Warning: Cannot resolve 'App'.
  App app = new App();
                ^^^
dart/web/map.dart:10:3:
Warning: Cannot resolve type 'MapApplication'.
  MapApplication map = new MapApplication();
  ^^^^^^^^^^^^^^
dart/web/map.dart:10:28:
Warning: Cannot resolve 'MapApplication'.
  MapApplication map = new MapApplication();
                           ^^^^^^^^^^^^^^
Error: Compilation failed.
  [ERROR] _temp/script-map.dart.js: openFile: does not exist (No such file or directory)
root@AR:/usr/local/dikmax.name-site#

so how to completely get rid of dart stuff?
